# Anna KaRNNa

In this notebook, we'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [1]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf
print(tf.__version__)

1.1.0


First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [2]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = set(text)
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [4]:
encoded[:100]

array([20, 12, 71, 52, 21, 36, 31, 32, 23, 40, 40, 40,  0, 71, 52, 52, 33,
       32, 18, 71, 58, 68, 41, 68, 36, 24, 32, 71, 31, 36, 32, 71, 41, 41,
       32, 71, 41, 68, 76, 36, 22, 32, 36, 29, 36, 31, 33, 32, 78, 64, 12,
       71, 52, 52, 33, 32, 18, 71, 58, 68, 41, 33, 32, 68, 24, 32, 78, 64,
       12, 71, 52, 52, 33, 32, 68, 64, 32, 68, 21, 24, 32, 44, 53, 64, 40,
       53, 71, 33,  1, 40, 40, 46, 29, 36, 31, 33, 21, 12, 68, 64], dtype=int32)

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [5]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

> **Exercise:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [6]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from (1-D Array)
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the batch size and number of batches we can make
    batch_size = n_seqs * n_steps # single batch size
    n_batches = len(arr) // batch_size # /: floating division, //: floor division
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * batch_size] # make divisable by batch_size?
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs, -1)) # -1 will automatically fit the dimension
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [7]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [8]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[20 12 71 52 21 36 31 32 23 40]
 [32 71 58 32 64 44 21 32  2 44]
 [29 68 64  1 40 40 35  6 36 24]
 [64 32 43 78 31 68 64  2 32 12]
 [32 68 21 32 68 24 37 32 24 68]
 [32 13 21 32 53 71 24 40 44 64]
 [12 36 64 32  8 44 58 36 32 18]
 [22 32 16 78 21 32 64 44 53 32]
 [21 32 68 24 64 74 21  1 32 10]
 [32 24 71 68 43 32 21 44 32 12]]

y
 [[12 71 52 21 36 31 32 23 40 40]
 [71 58 32 64 44 21 32  2 44 68]
 [68 64  1 40 40 35  6 36 24 37]
 [32 43 78 31 68 64  2 32 12 68]
 [68 21 32 68 24 37 32 24 68 31]
 [13 21 32 53 71 24 40 44 64 41]
 [36 64 32  8 44 58 36 32 18 44]
 [32 16 78 21 32 64 44 53 32 24]
 [32 68 24 64 74 21  1 32 10 12]
 [24 71 68 43 32 21 44 32 12 36]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`. This will be a scalar, that is a 0-D tensor. To make a scalar, you create a placeholder without giving it a size.

> **Exercise:** Create the input placeholders in the function below.

In [9]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. For example,

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow will create different weight matrices for all `cell` objects. Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

> **Exercise:** Below, implement the `build_lstm` function to create these LSTM cells and the initial state.

In [10]:
def build_lstm(lstm_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    # Use a basic LSTM cell
    lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
    
    # Add dropout to the cell outputs
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    return drop

def build_lstm_bug_fixed(lstm_size, keep_prob, num_layers, batch_size):
    # Stack up multiple LSTM layers, for deep learning
    # cell = tf.contrib.rnn.MultiRNNCell([drop] * num_layers)
    cell = tf.contrib.rnn.MultiRNNCell( [build_lstm(lstm_size, keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state( batch_size, tf.float32 )
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character, so we want this layer to have size $C$, the number of classes/characters we have in our text.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$. 

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells. We get the LSTM output as a list, `lstm_output`. First we need to concatenate this whole list into one array with [`tf.concat`](https://www.tensorflow.org/api_docs/python/tf/concat). Then, reshape it (with `tf.reshape`) to size $(M * N) \times L$.

Once we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

> **Exercise:** Implement the output layer in the function below.

In [11]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        lstm_output: List of output tensors from the LSTM layer
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # Concatenate lstm_output over axis 1 (the columns)
    seq_output = tf.concat( lstm_output, axis=1 )
    # Reshape seq_output to a 2D tensor with lstm_size columns
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        # Create the weight and bias variables here
        softmax_w = tf.Variable( tf.truncated_normal( (in_size, out_size), stddev=0.1 ) )
        softmax_b = tf.Variable( tf.zeros(out_size) )
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul( x, softmax_w ) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits=logits, name='predictions')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

>**Exercise:** Implement the loss calculation in the function below.

In [12]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per sequence per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped =  tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    loss = tf.reduce_mean(loss)
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [13]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

> **Exercise:** Use the functions you've implemented previously and `tf.nn.dynamic_rnn` to build the network.

In [14]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm_bug_fixed(lstm_size, self.keep_prob, num_layers, batch_size)
        #cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN with tf.nn.dynamic_rnn 
        outputs, state =tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss =  build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here are the hyperparameters for the network.

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

In [15]:
batch_size = 100        # Sequences per batch
num_steps = 50          # Number of sequence steps per batch
lstm_size = 256         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.01    # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

> **Exercise:** Set the hyperparameters above to train the network. Watch the training loss, it should be consistently dropping. Also, I highly advise running this on a GPU.

In [16]:
epochs = 20
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/20...  Training Step: 1...  Training loss: 4.4192...  1.5976 sec/batch
Epoch: 1/20...  Training Step: 2...  Training loss: 4.2296...  1.8657 sec/batch
Epoch: 1/20...  Training Step: 3...  Training loss: 3.8715...  1.7182 sec/batch
Epoch: 1/20...  Training Step: 4...  Training loss: 3.6019...  1.8860 sec/batch
Epoch: 1/20...  Training Step: 5...  Training loss: 3.5204...  1.3749 sec/batch
Epoch: 1/20...  Training Step: 6...  Training loss: 3.3612...  1.1557 sec/batch
Epoch: 1/20...  Training Step: 7...  Training loss: 3.2779...  0.9368 sec/batch
Epoch: 1/20...  Training Step: 8...  Training loss: 3.2628...  0.9603 sec/batch
Epoch: 1/20...  Training Step: 9...  Training loss: 3.2455...  0.9538 sec/batch
Epoch: 1/20...  Training Step: 10...  Training loss: 3.1975...  1.0923 sec/batch
Epoch: 1/20...  Training Step: 11...  Training loss: 3.1948...  0.9379 sec/batch
Epoch: 1/20...  Training Step: 12...  Training loss: 3.1766...  1.0559 sec/batch
Epoch: 1/20...  Training Step: 13... 

Epoch: 1/20...  Training Step: 103...  Training loss: 2.4165...  0.9301 sec/batch
Epoch: 1/20...  Training Step: 104...  Training loss: 2.3783...  0.9337 sec/batch
Epoch: 1/20...  Training Step: 105...  Training loss: 2.3933...  0.9398 sec/batch
Epoch: 1/20...  Training Step: 106...  Training loss: 2.3914...  0.9260 sec/batch
Epoch: 1/20...  Training Step: 107...  Training loss: 2.3894...  0.9350 sec/batch
Epoch: 1/20...  Training Step: 108...  Training loss: 2.3849...  0.9270 sec/batch
Epoch: 1/20...  Training Step: 109...  Training loss: 2.4075...  0.9246 sec/batch
Epoch: 1/20...  Training Step: 110...  Training loss: 2.3791...  0.9341 sec/batch
Epoch: 1/20...  Training Step: 111...  Training loss: 2.3892...  0.9304 sec/batch
Epoch: 1/20...  Training Step: 112...  Training loss: 2.3497...  0.9313 sec/batch
Epoch: 1/20...  Training Step: 113...  Training loss: 2.3475...  0.9362 sec/batch
Epoch: 1/20...  Training Step: 114...  Training loss: 2.3741...  0.9160 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 203...  Training loss: 2.0462...  0.9510 sec/batch
Epoch: 1/20...  Training Step: 204...  Training loss: 2.0802...  0.9359 sec/batch
Epoch: 1/20...  Training Step: 205...  Training loss: 2.0407...  0.9262 sec/batch
Epoch: 1/20...  Training Step: 206...  Training loss: 2.0909...  0.9336 sec/batch
Epoch: 1/20...  Training Step: 207...  Training loss: 2.0326...  0.9301 sec/batch
Epoch: 1/20...  Training Step: 208...  Training loss: 2.0485...  0.9419 sec/batch
Epoch: 1/20...  Training Step: 209...  Training loss: 2.0268...  0.9397 sec/batch
Epoch: 1/20...  Training Step: 210...  Training loss: 2.0191...  0.9279 sec/batch
Epoch: 1/20...  Training Step: 211...  Training loss: 2.0761...  0.9352 sec/batch
Epoch: 1/20...  Training Step: 212...  Training loss: 2.0718...  0.9339 sec/batch
Epoch: 1/20...  Training Step: 213...  Training loss: 2.0631...  0.9265 sec/batch
Epoch: 1/20...  Training Step: 214...  Training loss: 2.0457...  0.9289 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 303...  Training loss: 1.8635...  0.9306 sec/batch
Epoch: 1/20...  Training Step: 304...  Training loss: 1.8494...  0.9268 sec/batch
Epoch: 1/20...  Training Step: 305...  Training loss: 1.8666...  0.9322 sec/batch
Epoch: 1/20...  Training Step: 306...  Training loss: 1.8780...  0.9327 sec/batch
Epoch: 1/20...  Training Step: 307...  Training loss: 1.8754...  0.9209 sec/batch
Epoch: 1/20...  Training Step: 308...  Training loss: 1.8836...  0.9317 sec/batch
Epoch: 1/20...  Training Step: 309...  Training loss: 1.8918...  0.9273 sec/batch
Epoch: 1/20...  Training Step: 310...  Training loss: 1.9108...  0.9321 sec/batch
Epoch: 1/20...  Training Step: 311...  Training loss: 1.8344...  0.9326 sec/batch
Epoch: 1/20...  Training Step: 312...  Training loss: 1.9021...  0.9351 sec/batch
Epoch: 1/20...  Training Step: 313...  Training loss: 1.8948...  0.9344 sec/batch
Epoch: 1/20...  Training Step: 314...  Training loss: 1.9172...  0.9311 sec/batch
Epoch: 1/20...  

Epoch: 2/20...  Training Step: 403...  Training loss: 1.7538...  0.9408 sec/batch
Epoch: 2/20...  Training Step: 404...  Training loss: 1.7880...  0.9483 sec/batch
Epoch: 2/20...  Training Step: 405...  Training loss: 1.7864...  0.9355 sec/batch
Epoch: 2/20...  Training Step: 406...  Training loss: 1.8133...  0.9372 sec/batch
Epoch: 2/20...  Training Step: 407...  Training loss: 1.7750...  0.9300 sec/batch
Epoch: 2/20...  Training Step: 408...  Training loss: 1.8147...  0.9476 sec/batch
Epoch: 2/20...  Training Step: 409...  Training loss: 1.7822...  0.9363 sec/batch
Epoch: 2/20...  Training Step: 410...  Training loss: 1.8021...  0.9297 sec/batch
Epoch: 2/20...  Training Step: 411...  Training loss: 1.7563...  0.9314 sec/batch
Epoch: 2/20...  Training Step: 412...  Training loss: 1.7464...  0.9237 sec/batch
Epoch: 2/20...  Training Step: 413...  Training loss: 1.7419...  0.9425 sec/batch
Epoch: 2/20...  Training Step: 414...  Training loss: 1.7954...  0.9384 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 503...  Training loss: 1.7098...  0.9475 sec/batch
Epoch: 2/20...  Training Step: 504...  Training loss: 1.6948...  0.9798 sec/batch
Epoch: 2/20...  Training Step: 505...  Training loss: 1.7036...  0.9352 sec/batch
Epoch: 2/20...  Training Step: 506...  Training loss: 1.7022...  0.9581 sec/batch
Epoch: 2/20...  Training Step: 507...  Training loss: 1.7376...  0.9234 sec/batch
Epoch: 2/20...  Training Step: 508...  Training loss: 1.7008...  0.9244 sec/batch
Epoch: 2/20...  Training Step: 509...  Training loss: 1.7427...  0.9342 sec/batch
Epoch: 2/20...  Training Step: 510...  Training loss: 1.6948...  0.9317 sec/batch
Epoch: 2/20...  Training Step: 511...  Training loss: 1.7440...  0.9386 sec/batch
Epoch: 2/20...  Training Step: 512...  Training loss: 1.7555...  0.9314 sec/batch
Epoch: 2/20...  Training Step: 513...  Training loss: 1.7194...  0.9275 sec/batch
Epoch: 2/20...  Training Step: 514...  Training loss: 1.7294...  0.9340 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 603...  Training loss: 1.6852...  1.0566 sec/batch
Epoch: 2/20...  Training Step: 604...  Training loss: 1.6424...  1.0495 sec/batch
Epoch: 2/20...  Training Step: 605...  Training loss: 1.6613...  1.8347 sec/batch
Epoch: 2/20...  Training Step: 606...  Training loss: 1.6353...  0.9788 sec/batch
Epoch: 2/20...  Training Step: 607...  Training loss: 1.6118...  1.6428 sec/batch
Epoch: 2/20...  Training Step: 608...  Training loss: 1.6737...  1.0969 sec/batch
Epoch: 2/20...  Training Step: 609...  Training loss: 1.6776...  1.2292 sec/batch
Epoch: 2/20...  Training Step: 610...  Training loss: 1.6442...  0.9551 sec/batch
Epoch: 2/20...  Training Step: 611...  Training loss: 1.6750...  1.1868 sec/batch
Epoch: 2/20...  Training Step: 612...  Training loss: 1.6441...  1.0277 sec/batch
Epoch: 2/20...  Training Step: 613...  Training loss: 1.6648...  0.9389 sec/batch
Epoch: 2/20...  Training Step: 614...  Training loss: 1.6783...  0.9295 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 703...  Training loss: 1.5951...  0.9371 sec/batch
Epoch: 2/20...  Training Step: 704...  Training loss: 1.6072...  0.9300 sec/batch
Epoch: 2/20...  Training Step: 705...  Training loss: 1.6353...  0.9248 sec/batch
Epoch: 2/20...  Training Step: 706...  Training loss: 1.6492...  0.9346 sec/batch
Epoch: 2/20...  Training Step: 707...  Training loss: 1.6844...  0.9357 sec/batch
Epoch: 2/20...  Training Step: 708...  Training loss: 1.5896...  0.9390 sec/batch
Epoch: 2/20...  Training Step: 709...  Training loss: 1.6458...  0.9306 sec/batch
Epoch: 2/20...  Training Step: 710...  Training loss: 1.6663...  0.9239 sec/batch
Epoch: 2/20...  Training Step: 711...  Training loss: 1.6993...  0.9178 sec/batch
Epoch: 2/20...  Training Step: 712...  Training loss: 1.6419...  0.9345 sec/batch
Epoch: 2/20...  Training Step: 713...  Training loss: 1.6386...  0.9262 sec/batch
Epoch: 2/20...  Training Step: 714...  Training loss: 1.6372...  0.9396 sec/batch
Epoch: 2/20...  

Epoch: 3/20...  Training Step: 803...  Training loss: 1.6284...  0.9648 sec/batch
Epoch: 3/20...  Training Step: 804...  Training loss: 1.6146...  0.9326 sec/batch
Epoch: 3/20...  Training Step: 805...  Training loss: 1.6493...  0.9318 sec/batch
Epoch: 3/20...  Training Step: 806...  Training loss: 1.6114...  0.9328 sec/batch
Epoch: 3/20...  Training Step: 807...  Training loss: 1.6060...  0.9263 sec/batch
Epoch: 3/20...  Training Step: 808...  Training loss: 1.5879...  0.9333 sec/batch
Epoch: 3/20...  Training Step: 809...  Training loss: 1.5760...  0.9329 sec/batch
Epoch: 3/20...  Training Step: 810...  Training loss: 1.5729...  0.9316 sec/batch
Epoch: 3/20...  Training Step: 811...  Training loss: 1.6090...  0.9264 sec/batch
Epoch: 3/20...  Training Step: 812...  Training loss: 1.5680...  0.9345 sec/batch
Epoch: 3/20...  Training Step: 813...  Training loss: 1.5993...  0.9391 sec/batch
Epoch: 3/20...  Training Step: 814...  Training loss: 1.6431...  0.9338 sec/batch
Epoch: 3/20...  

Epoch: 3/20...  Training Step: 903...  Training loss: 1.5639...  0.9324 sec/batch
Epoch: 3/20...  Training Step: 904...  Training loss: 1.6114...  0.9288 sec/batch
Epoch: 3/20...  Training Step: 905...  Training loss: 1.5760...  0.9296 sec/batch
Epoch: 3/20...  Training Step: 906...  Training loss: 1.6023...  0.9370 sec/batch
Epoch: 3/20...  Training Step: 907...  Training loss: 1.5783...  0.9295 sec/batch
Epoch: 3/20...  Training Step: 908...  Training loss: 1.6051...  0.9265 sec/batch
Epoch: 3/20...  Training Step: 909...  Training loss: 1.6260...  0.9387 sec/batch
Epoch: 3/20...  Training Step: 910...  Training loss: 1.5717...  0.9385 sec/batch
Epoch: 3/20...  Training Step: 911...  Training loss: 1.5815...  0.9454 sec/batch
Epoch: 3/20...  Training Step: 912...  Training loss: 1.6135...  0.9387 sec/batch
Epoch: 3/20...  Training Step: 913...  Training loss: 1.6264...  0.9359 sec/batch
Epoch: 3/20...  Training Step: 914...  Training loss: 1.5960...  0.9348 sec/batch
Epoch: 3/20...  

Epoch: 3/20...  Training Step: 1003...  Training loss: 1.5363...  0.9625 sec/batch
Epoch: 3/20...  Training Step: 1004...  Training loss: 1.4921...  0.9226 sec/batch
Epoch: 3/20...  Training Step: 1005...  Training loss: 1.5843...  0.9304 sec/batch
Epoch: 3/20...  Training Step: 1006...  Training loss: 1.5673...  0.9335 sec/batch
Epoch: 3/20...  Training Step: 1007...  Training loss: 1.5593...  0.9382 sec/batch
Epoch: 3/20...  Training Step: 1008...  Training loss: 1.5558...  0.9367 sec/batch
Epoch: 3/20...  Training Step: 1009...  Training loss: 1.5347...  0.9354 sec/batch
Epoch: 3/20...  Training Step: 1010...  Training loss: 1.5781...  0.9369 sec/batch
Epoch: 3/20...  Training Step: 1011...  Training loss: 1.5941...  0.9962 sec/batch
Epoch: 3/20...  Training Step: 1012...  Training loss: 1.5854...  0.9415 sec/batch
Epoch: 3/20...  Training Step: 1013...  Training loss: 1.5561...  0.9626 sec/batch
Epoch: 3/20...  Training Step: 1014...  Training loss: 1.5747...  0.9326 sec/batch
Epoc

Epoch: 3/20...  Training Step: 1102...  Training loss: 1.5435...  0.9251 sec/batch
Epoch: 3/20...  Training Step: 1103...  Training loss: 1.5724...  0.9415 sec/batch
Epoch: 3/20...  Training Step: 1104...  Training loss: 1.6140...  0.9279 sec/batch
Epoch: 3/20...  Training Step: 1105...  Training loss: 1.5074...  0.9369 sec/batch
Epoch: 3/20...  Training Step: 1106...  Training loss: 1.5649...  0.9372 sec/batch
Epoch: 3/20...  Training Step: 1107...  Training loss: 1.5696...  0.9318 sec/batch
Epoch: 3/20...  Training Step: 1108...  Training loss: 1.5946...  0.9391 sec/batch
Epoch: 3/20...  Training Step: 1109...  Training loss: 1.5654...  0.9299 sec/batch
Epoch: 3/20...  Training Step: 1110...  Training loss: 1.5679...  0.9288 sec/batch
Epoch: 3/20...  Training Step: 1111...  Training loss: 1.5548...  0.9326 sec/batch
Epoch: 3/20...  Training Step: 1112...  Training loss: 1.5672...  0.9241 sec/batch
Epoch: 3/20...  Training Step: 1113...  Training loss: 1.5305...  0.9263 sec/batch
Epoc

Epoch: 4/20...  Training Step: 1201...  Training loss: 1.5270...  0.9127 sec/batch
Epoch: 4/20...  Training Step: 1202...  Training loss: 1.5584...  0.9432 sec/batch
Epoch: 4/20...  Training Step: 1203...  Training loss: 1.5215...  0.9531 sec/batch
Epoch: 4/20...  Training Step: 1204...  Training loss: 1.5430...  0.9433 sec/batch
Epoch: 4/20...  Training Step: 1205...  Training loss: 1.5351...  0.9299 sec/batch
Epoch: 4/20...  Training Step: 1206...  Training loss: 1.5035...  0.9292 sec/batch
Epoch: 4/20...  Training Step: 1207...  Training loss: 1.5130...  0.9373 sec/batch
Epoch: 4/20...  Training Step: 1208...  Training loss: 1.5501...  0.9326 sec/batch
Epoch: 4/20...  Training Step: 1209...  Training loss: 1.5055...  0.9379 sec/batch
Epoch: 4/20...  Training Step: 1210...  Training loss: 1.5298...  0.9364 sec/batch
Epoch: 4/20...  Training Step: 1211...  Training loss: 1.5724...  0.9347 sec/batch
Epoch: 4/20...  Training Step: 1212...  Training loss: 1.5441...  0.9228 sec/batch
Epoc

Epoch: 4/20...  Training Step: 1300...  Training loss: 1.4811...  0.9405 sec/batch
Epoch: 4/20...  Training Step: 1301...  Training loss: 1.5294...  0.9220 sec/batch
Epoch: 4/20...  Training Step: 1302...  Training loss: 1.5014...  0.9301 sec/batch
Epoch: 4/20...  Training Step: 1303...  Training loss: 1.5697...  0.9261 sec/batch
Epoch: 4/20...  Training Step: 1304...  Training loss: 1.5340...  0.9300 sec/batch
Epoch: 4/20...  Training Step: 1305...  Training loss: 1.5339...  0.9525 sec/batch
Epoch: 4/20...  Training Step: 1306...  Training loss: 1.5637...  0.9321 sec/batch
Epoch: 4/20...  Training Step: 1307...  Training loss: 1.5322...  0.9333 sec/batch
Epoch: 4/20...  Training Step: 1308...  Training loss: 1.5298...  0.9147 sec/batch
Epoch: 4/20...  Training Step: 1309...  Training loss: 1.5509...  0.9291 sec/batch
Epoch: 4/20...  Training Step: 1310...  Training loss: 1.5683...  0.9369 sec/batch
Epoch: 4/20...  Training Step: 1311...  Training loss: 1.5492...  0.9424 sec/batch
Epoc

Epoch: 4/20...  Training Step: 1399...  Training loss: 1.4973...  0.9321 sec/batch
Epoch: 4/20...  Training Step: 1400...  Training loss: 1.4916...  0.9252 sec/batch
Epoch: 4/20...  Training Step: 1401...  Training loss: 1.4729...  0.9229 sec/batch
Epoch: 4/20...  Training Step: 1402...  Training loss: 1.5332...  0.9459 sec/batch
Epoch: 4/20...  Training Step: 1403...  Training loss: 1.5226...  0.9664 sec/batch
Epoch: 4/20...  Training Step: 1404...  Training loss: 1.5023...  0.9320 sec/batch
Epoch: 4/20...  Training Step: 1405...  Training loss: 1.5145...  0.9384 sec/batch
Epoch: 4/20...  Training Step: 1406...  Training loss: 1.4986...  0.9454 sec/batch
Epoch: 4/20...  Training Step: 1407...  Training loss: 1.5336...  0.9519 sec/batch
Epoch: 4/20...  Training Step: 1408...  Training loss: 1.5484...  0.9323 sec/batch
Epoch: 4/20...  Training Step: 1409...  Training loss: 1.5258...  0.9308 sec/batch
Epoch: 4/20...  Training Step: 1410...  Training loss: 1.5005...  0.9387 sec/batch
Epoc

Epoch: 4/20...  Training Step: 1498...  Training loss: 1.4842...  0.9326 sec/batch
Epoch: 4/20...  Training Step: 1499...  Training loss: 1.5016...  0.9317 sec/batch
Epoch: 4/20...  Training Step: 1500...  Training loss: 1.5223...  0.9270 sec/batch
Epoch: 4/20...  Training Step: 1501...  Training loss: 1.5544...  0.9241 sec/batch
Epoch: 4/20...  Training Step: 1502...  Training loss: 1.4589...  0.9315 sec/batch
Epoch: 4/20...  Training Step: 1503...  Training loss: 1.5180...  0.9343 sec/batch
Epoch: 4/20...  Training Step: 1504...  Training loss: 1.5374...  0.9386 sec/batch
Epoch: 4/20...  Training Step: 1505...  Training loss: 1.5529...  0.9239 sec/batch
Epoch: 4/20...  Training Step: 1506...  Training loss: 1.5251...  0.9357 sec/batch
Epoch: 4/20...  Training Step: 1507...  Training loss: 1.5083...  0.9352 sec/batch
Epoch: 4/20...  Training Step: 1508...  Training loss: 1.5183...  0.9388 sec/batch
Epoch: 4/20...  Training Step: 1509...  Training loss: 1.5313...  0.9360 sec/batch
Epoc

Epoch: 5/20...  Training Step: 1597...  Training loss: 1.4973...  0.9306 sec/batch
Epoch: 5/20...  Training Step: 1598...  Training loss: 1.5036...  0.9306 sec/batch
Epoch: 5/20...  Training Step: 1599...  Training loss: 1.5314...  0.9460 sec/batch
Epoch: 5/20...  Training Step: 1600...  Training loss: 1.5053...  0.9309 sec/batch
Epoch: 5/20...  Training Step: 1601...  Training loss: 1.4893...  0.9124 sec/batch
Epoch: 5/20...  Training Step: 1602...  Training loss: 1.4815...  0.9369 sec/batch
Epoch: 5/20...  Training Step: 1603...  Training loss: 1.4595...  0.9514 sec/batch
Epoch: 5/20...  Training Step: 1604...  Training loss: 1.4652...  0.9369 sec/batch
Epoch: 5/20...  Training Step: 1605...  Training loss: 1.5042...  0.9372 sec/batch
Epoch: 5/20...  Training Step: 1606...  Training loss: 1.4675...  0.9403 sec/batch
Epoch: 5/20...  Training Step: 1607...  Training loss: 1.5061...  0.9395 sec/batch
Epoch: 5/20...  Training Step: 1608...  Training loss: 1.5274...  0.9372 sec/batch
Epoc

Epoch: 5/20...  Training Step: 1696...  Training loss: 1.4775...  0.9179 sec/batch
Epoch: 5/20...  Training Step: 1697...  Training loss: 1.4620...  0.9194 sec/batch
Epoch: 5/20...  Training Step: 1698...  Training loss: 1.4931...  0.9216 sec/batch
Epoch: 5/20...  Training Step: 1699...  Training loss: 1.4675...  0.9194 sec/batch
Epoch: 5/20...  Training Step: 1700...  Training loss: 1.5228...  0.9356 sec/batch
Epoch: 5/20...  Training Step: 1701...  Training loss: 1.4818...  0.9310 sec/batch
Epoch: 5/20...  Training Step: 1702...  Training loss: 1.5041...  0.9378 sec/batch
Epoch: 5/20...  Training Step: 1703...  Training loss: 1.5384...  0.9326 sec/batch
Epoch: 5/20...  Training Step: 1704...  Training loss: 1.4903...  0.9278 sec/batch
Epoch: 5/20...  Training Step: 1705...  Training loss: 1.5196...  0.9315 sec/batch
Epoch: 5/20...  Training Step: 1706...  Training loss: 1.5214...  0.9274 sec/batch
Epoch: 5/20...  Training Step: 1707...  Training loss: 1.5211...  0.9369 sec/batch
Epoc

Epoch: 5/20...  Training Step: 1795...  Training loss: 1.4637...  0.9322 sec/batch
Epoch: 5/20...  Training Step: 1796...  Training loss: 1.4707...  0.9451 sec/batch
Epoch: 5/20...  Training Step: 1797...  Training loss: 1.4585...  0.9322 sec/batch
Epoch: 5/20...  Training Step: 1798...  Training loss: 1.4280...  0.9371 sec/batch
Epoch: 5/20...  Training Step: 1799...  Training loss: 1.5097...  0.9208 sec/batch
Epoch: 5/20...  Training Step: 1800...  Training loss: 1.4922...  0.9264 sec/batch
Epoch: 5/20...  Training Step: 1801...  Training loss: 1.4766...  0.9043 sec/batch
Epoch: 5/20...  Training Step: 1802...  Training loss: 1.4893...  0.9460 sec/batch
Epoch: 5/20...  Training Step: 1803...  Training loss: 1.4384...  0.9524 sec/batch
Epoch: 5/20...  Training Step: 1804...  Training loss: 1.4891...  0.9278 sec/batch
Epoch: 5/20...  Training Step: 1805...  Training loss: 1.4939...  0.9280 sec/batch
Epoch: 5/20...  Training Step: 1806...  Training loss: 1.4827...  0.9396 sec/batch
Epoc

Epoch: 5/20...  Training Step: 1894...  Training loss: 1.4508...  1.1904 sec/batch
Epoch: 5/20...  Training Step: 1895...  Training loss: 1.4647...  1.2250 sec/batch
Epoch: 5/20...  Training Step: 1896...  Training loss: 1.4919...  1.1903 sec/batch
Epoch: 5/20...  Training Step: 1897...  Training loss: 1.4925...  1.2166 sec/batch
Epoch: 5/20...  Training Step: 1898...  Training loss: 1.5425...  1.2965 sec/batch
Epoch: 5/20...  Training Step: 1899...  Training loss: 1.4249...  1.7880 sec/batch
Epoch: 5/20...  Training Step: 1900...  Training loss: 1.4909...  1.1950 sec/batch
Epoch: 5/20...  Training Step: 1901...  Training loss: 1.5172...  0.9444 sec/batch
Epoch: 5/20...  Training Step: 1902...  Training loss: 1.5068...  0.9623 sec/batch
Epoch: 5/20...  Training Step: 1903...  Training loss: 1.5022...  0.9729 sec/batch
Epoch: 5/20...  Training Step: 1904...  Training loss: 1.4957...  1.1950 sec/batch
Epoch: 5/20...  Training Step: 1905...  Training loss: 1.4798...  1.1206 sec/batch
Epoc

Epoch: 6/20...  Training Step: 1993...  Training loss: 1.4660...  0.9576 sec/batch
Epoch: 6/20...  Training Step: 1994...  Training loss: 1.4857...  0.9369 sec/batch
Epoch: 6/20...  Training Step: 1995...  Training loss: 1.4810...  1.2251 sec/batch
Epoch: 6/20...  Training Step: 1996...  Training loss: 1.5055...  1.1206 sec/batch
Epoch: 6/20...  Training Step: 1997...  Training loss: 1.4787...  0.9499 sec/batch
Epoch: 6/20...  Training Step: 1998...  Training loss: 1.4765...  0.9551 sec/batch
Epoch: 6/20...  Training Step: 1999...  Training loss: 1.4826...  1.0178 sec/batch
Epoch: 6/20...  Training Step: 2000...  Training loss: 1.4378...  1.2359 sec/batch
Epoch: 6/20...  Training Step: 2001...  Training loss: 1.4480...  0.9339 sec/batch
Epoch: 6/20...  Training Step: 2002...  Training loss: 1.4713...  0.9492 sec/batch
Epoch: 6/20...  Training Step: 2003...  Training loss: 1.4416...  0.9709 sec/batch
Epoch: 6/20...  Training Step: 2004...  Training loss: 1.4684...  1.2117 sec/batch
Epoc

Epoch: 6/20...  Training Step: 2092...  Training loss: 1.4341...  1.0178 sec/batch
Epoch: 6/20...  Training Step: 2093...  Training loss: 1.4278...  0.9415 sec/batch
Epoch: 6/20...  Training Step: 2094...  Training loss: 1.4293...  0.9513 sec/batch
Epoch: 6/20...  Training Step: 2095...  Training loss: 1.4771...  1.0667 sec/batch
Epoch: 6/20...  Training Step: 2096...  Training loss: 1.4444...  1.2156 sec/batch
Epoch: 6/20...  Training Step: 2097...  Training loss: 1.5060...  0.9843 sec/batch
Epoch: 6/20...  Training Step: 2098...  Training loss: 1.4698...  0.9434 sec/batch
Epoch: 6/20...  Training Step: 2099...  Training loss: 1.4980...  0.9517 sec/batch
Epoch: 6/20...  Training Step: 2100...  Training loss: 1.5163...  1.1089 sec/batch
Epoch: 6/20...  Training Step: 2101...  Training loss: 1.4688...  1.1914 sec/batch
Epoch: 6/20...  Training Step: 2102...  Training loss: 1.4829...  0.9411 sec/batch
Epoch: 6/20...  Training Step: 2103...  Training loss: 1.4967...  0.9482 sec/batch
Epoc

Epoch: 6/20...  Training Step: 2191...  Training loss: 1.4732...  0.9509 sec/batch
Epoch: 6/20...  Training Step: 2192...  Training loss: 1.4477...  1.1536 sec/batch
Epoch: 6/20...  Training Step: 2193...  Training loss: 1.4382...  1.1715 sec/batch
Epoch: 6/20...  Training Step: 2194...  Training loss: 1.4501...  0.9646 sec/batch
Epoch: 6/20...  Training Step: 2195...  Training loss: 1.3888...  0.9567 sec/batch
Epoch: 6/20...  Training Step: 2196...  Training loss: 1.4808...  0.9554 sec/batch
Epoch: 6/20...  Training Step: 2197...  Training loss: 1.4551...  1.2091 sec/batch
Epoch: 6/20...  Training Step: 2198...  Training loss: 1.4630...  1.0868 sec/batch
Epoch: 6/20...  Training Step: 2199...  Training loss: 1.4357...  0.9359 sec/batch
Epoch: 6/20...  Training Step: 2200...  Training loss: 1.4367...  0.9531 sec/batch
Epoch: 6/20...  Training Step: 2201...  Training loss: 1.4681...  1.1320 sec/batch
Epoch: 6/20...  Training Step: 2202...  Training loss: 1.4809...  1.1227 sec/batch
Epoc

Epoch: 6/20...  Training Step: 2290...  Training loss: 1.4394...  0.9434 sec/batch
Epoch: 6/20...  Training Step: 2291...  Training loss: 1.4291...  0.9521 sec/batch
Epoch: 6/20...  Training Step: 2292...  Training loss: 1.4455...  1.0297 sec/batch
Epoch: 6/20...  Training Step: 2293...  Training loss: 1.4510...  1.1985 sec/batch
Epoch: 6/20...  Training Step: 2294...  Training loss: 1.4587...  1.0237 sec/batch
Epoch: 6/20...  Training Step: 2295...  Training loss: 1.5026...  0.9585 sec/batch
Epoch: 6/20...  Training Step: 2296...  Training loss: 1.4092...  0.9554 sec/batch
Epoch: 6/20...  Training Step: 2297...  Training loss: 1.4626...  1.0935 sec/batch
Epoch: 6/20...  Training Step: 2298...  Training loss: 1.4868...  1.1916 sec/batch
Epoch: 6/20...  Training Step: 2299...  Training loss: 1.4897...  0.9664 sec/batch
Epoch: 6/20...  Training Step: 2300...  Training loss: 1.4740...  0.9512 sec/batch
Epoch: 6/20...  Training Step: 2301...  Training loss: 1.4785...  0.9692 sec/batch
Epoc

Epoch: 7/20...  Training Step: 2389...  Training loss: 1.4484...  1.1172 sec/batch
Epoch: 7/20...  Training Step: 2390...  Training loss: 1.4560...  1.1699 sec/batch
Epoch: 7/20...  Training Step: 2391...  Training loss: 1.4452...  0.9375 sec/batch
Epoch: 7/20...  Training Step: 2392...  Training loss: 1.4551...  0.9468 sec/batch
Epoch: 7/20...  Training Step: 2393...  Training loss: 1.4890...  0.9585 sec/batch
Epoch: 7/20...  Training Step: 2394...  Training loss: 1.4563...  1.1503 sec/batch
Epoch: 7/20...  Training Step: 2395...  Training loss: 1.4512...  1.1336 sec/batch
Epoch: 7/20...  Training Step: 2396...  Training loss: 1.4524...  0.9490 sec/batch
Epoch: 7/20...  Training Step: 2397...  Training loss: 1.4147...  0.9650 sec/batch
Epoch: 7/20...  Training Step: 2398...  Training loss: 1.4348...  0.9466 sec/batch
Epoch: 7/20...  Training Step: 2399...  Training loss: 1.4510...  1.1819 sec/batch
Epoch: 7/20...  Training Step: 2400...  Training loss: 1.4291...  1.1053 sec/batch
Epoc

Epoch: 7/20...  Training Step: 2488...  Training loss: 1.4343...  0.9365 sec/batch
Epoch: 7/20...  Training Step: 2489...  Training loss: 1.4175...  0.9257 sec/batch
Epoch: 7/20...  Training Step: 2490...  Training loss: 1.4161...  0.9354 sec/batch
Epoch: 7/20...  Training Step: 2491...  Training loss: 1.4183...  0.9337 sec/batch
Epoch: 7/20...  Training Step: 2492...  Training loss: 1.4670...  0.9257 sec/batch
Epoch: 7/20...  Training Step: 2493...  Training loss: 1.4418...  0.9216 sec/batch
Epoch: 7/20...  Training Step: 2494...  Training loss: 1.4806...  0.9260 sec/batch
Epoch: 7/20...  Training Step: 2495...  Training loss: 1.4362...  0.9202 sec/batch
Epoch: 7/20...  Training Step: 2496...  Training loss: 1.4704...  0.9687 sec/batch
Epoch: 7/20...  Training Step: 2497...  Training loss: 1.5024...  0.9378 sec/batch
Epoch: 7/20...  Training Step: 2498...  Training loss: 1.4609...  0.9221 sec/batch
Epoch: 7/20...  Training Step: 2499...  Training loss: 1.4655...  0.9126 sec/batch
Epoc

Epoch: 7/20...  Training Step: 2587...  Training loss: 1.4300...  0.9275 sec/batch
Epoch: 7/20...  Training Step: 2588...  Training loss: 1.4374...  0.9315 sec/batch
Epoch: 7/20...  Training Step: 2589...  Training loss: 1.4214...  0.9247 sec/batch
Epoch: 7/20...  Training Step: 2590...  Training loss: 1.4173...  0.9243 sec/batch
Epoch: 7/20...  Training Step: 2591...  Training loss: 1.4222...  0.9176 sec/batch
Epoch: 7/20...  Training Step: 2592...  Training loss: 1.3842...  0.9260 sec/batch
Epoch: 7/20...  Training Step: 2593...  Training loss: 1.4793...  0.9340 sec/batch
Epoch: 7/20...  Training Step: 2594...  Training loss: 1.4494...  0.9322 sec/batch
Epoch: 7/20...  Training Step: 2595...  Training loss: 1.4380...  0.9094 sec/batch
Epoch: 7/20...  Training Step: 2596...  Training loss: 1.4430...  0.9247 sec/batch
Epoch: 7/20...  Training Step: 2597...  Training loss: 1.4069...  0.9210 sec/batch
Epoch: 7/20...  Training Step: 2598...  Training loss: 1.4489...  0.9192 sec/batch
Epoc

Epoch: 7/20...  Training Step: 2686...  Training loss: 1.4079...  0.9281 sec/batch
Epoch: 7/20...  Training Step: 2687...  Training loss: 1.4268...  0.9238 sec/batch
Epoch: 7/20...  Training Step: 2688...  Training loss: 1.4069...  0.9156 sec/batch
Epoch: 7/20...  Training Step: 2689...  Training loss: 1.4327...  0.9249 sec/batch
Epoch: 7/20...  Training Step: 2690...  Training loss: 1.4344...  0.9206 sec/batch
Epoch: 7/20...  Training Step: 2691...  Training loss: 1.4516...  0.9271 sec/batch
Epoch: 7/20...  Training Step: 2692...  Training loss: 1.4989...  0.9225 sec/batch
Epoch: 7/20...  Training Step: 2693...  Training loss: 1.4126...  0.9262 sec/batch
Epoch: 7/20...  Training Step: 2694...  Training loss: 1.4720...  0.9153 sec/batch
Epoch: 7/20...  Training Step: 2695...  Training loss: 1.4698...  0.9264 sec/batch
Epoch: 7/20...  Training Step: 2696...  Training loss: 1.4933...  0.9222 sec/batch
Epoch: 7/20...  Training Step: 2697...  Training loss: 1.4510...  0.9142 sec/batch
Epoc

Epoch: 8/20...  Training Step: 2785...  Training loss: 1.4034...  0.9260 sec/batch
Epoch: 8/20...  Training Step: 2786...  Training loss: 1.4375...  0.9291 sec/batch
Epoch: 8/20...  Training Step: 2787...  Training loss: 1.4421...  0.9381 sec/batch
Epoch: 8/20...  Training Step: 2788...  Training loss: 1.4530...  0.9266 sec/batch
Epoch: 8/20...  Training Step: 2789...  Training loss: 1.4355...  0.9235 sec/batch
Epoch: 8/20...  Training Step: 2790...  Training loss: 1.4729...  0.9139 sec/batch
Epoch: 8/20...  Training Step: 2791...  Training loss: 1.4389...  0.9212 sec/batch
Epoch: 8/20...  Training Step: 2792...  Training loss: 1.4340...  0.9252 sec/batch
Epoch: 8/20...  Training Step: 2793...  Training loss: 1.4552...  0.9271 sec/batch
Epoch: 8/20...  Training Step: 2794...  Training loss: 1.4016...  0.9253 sec/batch
Epoch: 8/20...  Training Step: 2795...  Training loss: 1.4131...  0.9233 sec/batch
Epoch: 8/20...  Training Step: 2796...  Training loss: 1.4595...  0.9191 sec/batch
Epoc

Epoch: 8/20...  Training Step: 2884...  Training loss: 1.4207...  0.9305 sec/batch
Epoch: 8/20...  Training Step: 2885...  Training loss: 1.4214...  0.9239 sec/batch
Epoch: 8/20...  Training Step: 2886...  Training loss: 1.4187...  0.9132 sec/batch
Epoch: 8/20...  Training Step: 2887...  Training loss: 1.4052...  0.9283 sec/batch
Epoch: 8/20...  Training Step: 2888...  Training loss: 1.4036...  0.9301 sec/batch
Epoch: 8/20...  Training Step: 2889...  Training loss: 1.4382...  0.9268 sec/batch
Epoch: 8/20...  Training Step: 2890...  Training loss: 1.4259...  0.9305 sec/batch
Epoch: 8/20...  Training Step: 2891...  Training loss: 1.4669...  0.9246 sec/batch
Epoch: 8/20...  Training Step: 2892...  Training loss: 1.4328...  0.9199 sec/batch
Epoch: 8/20...  Training Step: 2893...  Training loss: 1.4425...  0.9225 sec/batch
Epoch: 8/20...  Training Step: 2894...  Training loss: 1.4859...  0.9191 sec/batch
Epoch: 8/20...  Training Step: 2895...  Training loss: 1.4273...  0.9348 sec/batch
Epoc

Epoch: 8/20...  Training Step: 2983...  Training loss: 1.4886...  0.9243 sec/batch
Epoch: 8/20...  Training Step: 2984...  Training loss: 1.4169...  0.9200 sec/batch
Epoch: 8/20...  Training Step: 2985...  Training loss: 1.4462...  0.9223 sec/batch
Epoch: 8/20...  Training Step: 2986...  Training loss: 1.4154...  0.9341 sec/batch
Epoch: 8/20...  Training Step: 2987...  Training loss: 1.3921...  0.9297 sec/batch
Epoch: 8/20...  Training Step: 2988...  Training loss: 1.4079...  0.9200 sec/batch
Epoch: 8/20...  Training Step: 2989...  Training loss: 1.3690...  0.9199 sec/batch
Epoch: 8/20...  Training Step: 2990...  Training loss: 1.4686...  0.9249 sec/batch
Epoch: 8/20...  Training Step: 2991...  Training loss: 1.4401...  0.9202 sec/batch
Epoch: 8/20...  Training Step: 2992...  Training loss: 1.4160...  0.9261 sec/batch
Epoch: 8/20...  Training Step: 2993...  Training loss: 1.4315...  0.9197 sec/batch
Epoch: 8/20...  Training Step: 2994...  Training loss: 1.4004...  0.9225 sec/batch
Epoc

Epoch: 8/20...  Training Step: 3082...  Training loss: 1.4086...  0.9338 sec/batch
Epoch: 8/20...  Training Step: 3083...  Training loss: 1.4040...  0.9295 sec/batch
Epoch: 8/20...  Training Step: 3084...  Training loss: 1.4158...  0.9261 sec/batch
Epoch: 8/20...  Training Step: 3085...  Training loss: 1.3979...  0.9338 sec/batch
Epoch: 8/20...  Training Step: 3086...  Training loss: 1.4219...  0.9241 sec/batch
Epoch: 8/20...  Training Step: 3087...  Training loss: 1.4264...  0.9285 sec/batch
Epoch: 8/20...  Training Step: 3088...  Training loss: 1.4376...  0.9156 sec/batch
Epoch: 8/20...  Training Step: 3089...  Training loss: 1.4922...  0.9216 sec/batch
Epoch: 8/20...  Training Step: 3090...  Training loss: 1.4017...  0.9264 sec/batch
Epoch: 8/20...  Training Step: 3091...  Training loss: 1.4465...  0.9181 sec/batch
Epoch: 8/20...  Training Step: 3092...  Training loss: 1.4598...  0.9234 sec/batch
Epoch: 8/20...  Training Step: 3093...  Training loss: 1.4657...  0.9302 sec/batch
Epoc

Epoch: 9/20...  Training Step: 3181...  Training loss: 1.3900...  0.9249 sec/batch
Epoch: 9/20...  Training Step: 3182...  Training loss: 1.3908...  0.9233 sec/batch
Epoch: 9/20...  Training Step: 3183...  Training loss: 1.4103...  0.9215 sec/batch
Epoch: 9/20...  Training Step: 3184...  Training loss: 1.4321...  0.9151 sec/batch
Epoch: 9/20...  Training Step: 3185...  Training loss: 1.4379...  0.9336 sec/batch
Epoch: 9/20...  Training Step: 3186...  Training loss: 1.4287...  0.9265 sec/batch
Epoch: 9/20...  Training Step: 3187...  Training loss: 1.4516...  0.9309 sec/batch
Epoch: 9/20...  Training Step: 3188...  Training loss: 1.4323...  0.9225 sec/batch
Epoch: 9/20...  Training Step: 3189...  Training loss: 1.4184...  0.9269 sec/batch
Epoch: 9/20...  Training Step: 3190...  Training loss: 1.4315...  0.9325 sec/batch
Epoch: 9/20...  Training Step: 3191...  Training loss: 1.4016...  0.9222 sec/batch
Epoch: 9/20...  Training Step: 3192...  Training loss: 1.3877...  0.9247 sec/batch
Epoc

Epoch: 9/20...  Training Step: 3280...  Training loss: 1.4320...  0.9255 sec/batch
Epoch: 9/20...  Training Step: 3281...  Training loss: 1.4183...  0.9313 sec/batch
Epoch: 9/20...  Training Step: 3282...  Training loss: 1.4214...  0.9296 sec/batch
Epoch: 9/20...  Training Step: 3283...  Training loss: 1.4141...  0.9270 sec/batch
Epoch: 9/20...  Training Step: 3284...  Training loss: 1.3886...  0.9291 sec/batch
Epoch: 9/20...  Training Step: 3285...  Training loss: 1.3983...  0.9243 sec/batch
Epoch: 9/20...  Training Step: 3286...  Training loss: 1.4322...  0.9240 sec/batch
Epoch: 9/20...  Training Step: 3287...  Training loss: 1.4163...  0.9306 sec/batch
Epoch: 9/20...  Training Step: 3288...  Training loss: 1.4600...  0.9270 sec/batch
Epoch: 9/20...  Training Step: 3289...  Training loss: 1.4356...  0.9241 sec/batch
Epoch: 9/20...  Training Step: 3290...  Training loss: 1.4301...  0.9219 sec/batch
Epoch: 9/20...  Training Step: 3291...  Training loss: 1.4727...  0.9219 sec/batch
Epoc

Epoch: 9/20...  Training Step: 3379...  Training loss: 1.4026...  0.9166 sec/batch
Epoch: 9/20...  Training Step: 3380...  Training loss: 1.4777...  0.9176 sec/batch
Epoch: 9/20...  Training Step: 3381...  Training loss: 1.4010...  0.9290 sec/batch
Epoch: 9/20...  Training Step: 3382...  Training loss: 1.4343...  0.9312 sec/batch
Epoch: 9/20...  Training Step: 3383...  Training loss: 1.3993...  0.9248 sec/batch
Epoch: 9/20...  Training Step: 3384...  Training loss: 1.4015...  0.9418 sec/batch
Epoch: 9/20...  Training Step: 3385...  Training loss: 1.4074...  0.9293 sec/batch
Epoch: 9/20...  Training Step: 3386...  Training loss: 1.3621...  0.9219 sec/batch
Epoch: 9/20...  Training Step: 3387...  Training loss: 1.4434...  0.9246 sec/batch
Epoch: 9/20...  Training Step: 3388...  Training loss: 1.4184...  0.9269 sec/batch
Epoch: 9/20...  Training Step: 3389...  Training loss: 1.4267...  0.9235 sec/batch
Epoch: 9/20...  Training Step: 3390...  Training loss: 1.4199...  0.9388 sec/batch
Epoc

Epoch: 9/20...  Training Step: 3478...  Training loss: 1.4362...  0.9271 sec/batch
Epoch: 9/20...  Training Step: 3479...  Training loss: 1.3978...  0.9238 sec/batch
Epoch: 9/20...  Training Step: 3480...  Training loss: 1.3950...  0.9388 sec/batch
Epoch: 9/20...  Training Step: 3481...  Training loss: 1.4073...  0.9156 sec/batch
Epoch: 9/20...  Training Step: 3482...  Training loss: 1.3903...  0.9191 sec/batch
Epoch: 9/20...  Training Step: 3483...  Training loss: 1.4082...  0.9197 sec/batch
Epoch: 9/20...  Training Step: 3484...  Training loss: 1.4168...  0.9269 sec/batch
Epoch: 9/20...  Training Step: 3485...  Training loss: 1.4314...  0.9280 sec/batch
Epoch: 9/20...  Training Step: 3486...  Training loss: 1.4637...  0.9239 sec/batch
Epoch: 9/20...  Training Step: 3487...  Training loss: 1.3860...  0.9151 sec/batch
Epoch: 9/20...  Training Step: 3488...  Training loss: 1.4278...  0.9219 sec/batch
Epoch: 9/20...  Training Step: 3489...  Training loss: 1.4460...  0.9236 sec/batch
Epoc

Epoch: 10/20...  Training Step: 3577...  Training loss: 1.3684...  0.9887 sec/batch
Epoch: 10/20...  Training Step: 3578...  Training loss: 1.3637...  1.0304 sec/batch
Epoch: 10/20...  Training Step: 3579...  Training loss: 1.3902...  1.4467 sec/batch
Epoch: 10/20...  Training Step: 3580...  Training loss: 1.4047...  1.0058 sec/batch
Epoch: 10/20...  Training Step: 3581...  Training loss: 1.4200...  0.9832 sec/batch
Epoch: 10/20...  Training Step: 3582...  Training loss: 1.4323...  1.6320 sec/batch
Epoch: 10/20...  Training Step: 3583...  Training loss: 1.4212...  1.3955 sec/batch
Epoch: 10/20...  Training Step: 3584...  Training loss: 1.4532...  1.0978 sec/batch
Epoch: 10/20...  Training Step: 3585...  Training loss: 1.4283...  1.2114 sec/batch
Epoch: 10/20...  Training Step: 3586...  Training loss: 1.3995...  1.1743 sec/batch
Epoch: 10/20...  Training Step: 3587...  Training loss: 1.4145...  1.0340 sec/batch
Epoch: 10/20...  Training Step: 3588...  Training loss: 1.3854...  0.9304 se

Epoch: 10/20...  Training Step: 3675...  Training loss: 1.4165...  0.9319 sec/batch
Epoch: 10/20...  Training Step: 3676...  Training loss: 1.5008...  0.9229 sec/batch
Epoch: 10/20...  Training Step: 3677...  Training loss: 1.4283...  0.9288 sec/batch
Epoch: 10/20...  Training Step: 3678...  Training loss: 1.3925...  0.9322 sec/batch
Epoch: 10/20...  Training Step: 3679...  Training loss: 1.4087...  0.9282 sec/batch
Epoch: 10/20...  Training Step: 3680...  Training loss: 1.3926...  0.9324 sec/batch
Epoch: 10/20...  Training Step: 3681...  Training loss: 1.4010...  0.9307 sec/batch
Epoch: 10/20...  Training Step: 3682...  Training loss: 1.3920...  0.9225 sec/batch
Epoch: 10/20...  Training Step: 3683...  Training loss: 1.4222...  0.9391 sec/batch
Epoch: 10/20...  Training Step: 3684...  Training loss: 1.4099...  0.9158 sec/batch
Epoch: 10/20...  Training Step: 3685...  Training loss: 1.4565...  0.9398 sec/batch
Epoch: 10/20...  Training Step: 3686...  Training loss: 1.4308...  0.9345 se

Epoch: 10/20...  Training Step: 3773...  Training loss: 1.4420...  0.9292 sec/batch
Epoch: 10/20...  Training Step: 3774...  Training loss: 1.4421...  0.9263 sec/batch
Epoch: 10/20...  Training Step: 3775...  Training loss: 1.4419...  0.9308 sec/batch
Epoch: 10/20...  Training Step: 3776...  Training loss: 1.3874...  0.9319 sec/batch
Epoch: 10/20...  Training Step: 3777...  Training loss: 1.4570...  0.9294 sec/batch
Epoch: 10/20...  Training Step: 3778...  Training loss: 1.3823...  0.9291 sec/batch
Epoch: 10/20...  Training Step: 3779...  Training loss: 1.4086...  0.9296 sec/batch
Epoch: 10/20...  Training Step: 3780...  Training loss: 1.3878...  1.0120 sec/batch
Epoch: 10/20...  Training Step: 3781...  Training loss: 1.3865...  0.9388 sec/batch
Epoch: 10/20...  Training Step: 3782...  Training loss: 1.4005...  0.9855 sec/batch
Epoch: 10/20...  Training Step: 3783...  Training loss: 1.3467...  0.9265 sec/batch
Epoch: 10/20...  Training Step: 3784...  Training loss: 1.4521...  0.9478 se

Epoch: 10/20...  Training Step: 3871...  Training loss: 1.4727...  0.9283 sec/batch
Epoch: 10/20...  Training Step: 3872...  Training loss: 1.4322...  0.9325 sec/batch
Epoch: 10/20...  Training Step: 3873...  Training loss: 1.4065...  0.9272 sec/batch
Epoch: 10/20...  Training Step: 3874...  Training loss: 1.3941...  0.9283 sec/batch
Epoch: 10/20...  Training Step: 3875...  Training loss: 1.4263...  0.9258 sec/batch
Epoch: 10/20...  Training Step: 3876...  Training loss: 1.3915...  0.9326 sec/batch
Epoch: 10/20...  Training Step: 3877...  Training loss: 1.3927...  0.9315 sec/batch
Epoch: 10/20...  Training Step: 3878...  Training loss: 1.4042...  0.9351 sec/batch
Epoch: 10/20...  Training Step: 3879...  Training loss: 1.4001...  0.9207 sec/batch
Epoch: 10/20...  Training Step: 3880...  Training loss: 1.4154...  0.9178 sec/batch
Epoch: 10/20...  Training Step: 3881...  Training loss: 1.4029...  0.9299 sec/batch
Epoch: 10/20...  Training Step: 3882...  Training loss: 1.4368...  0.9300 se

Epoch: 10/20...  Training Step: 3969...  Training loss: 1.4298...  0.9305 sec/batch
Epoch: 10/20...  Training Step: 3970...  Training loss: 1.4321...  0.9461 sec/batch
Epoch: 11/20...  Training Step: 3971...  Training loss: 1.5126...  0.9304 sec/batch
Epoch: 11/20...  Training Step: 3972...  Training loss: 1.3721...  0.9342 sec/batch
Epoch: 11/20...  Training Step: 3973...  Training loss: 1.4301...  0.9463 sec/batch
Epoch: 11/20...  Training Step: 3974...  Training loss: 1.3731...  0.9437 sec/batch
Epoch: 11/20...  Training Step: 3975...  Training loss: 1.3802...  0.9407 sec/batch
Epoch: 11/20...  Training Step: 3976...  Training loss: 1.3771...  0.9369 sec/batch
Epoch: 11/20...  Training Step: 3977...  Training loss: 1.3873...  0.9341 sec/batch
Epoch: 11/20...  Training Step: 3978...  Training loss: 1.4019...  0.9340 sec/batch
Epoch: 11/20...  Training Step: 3979...  Training loss: 1.4046...  0.9344 sec/batch
Epoch: 11/20...  Training Step: 3980...  Training loss: 1.4182...  0.9197 se

Epoch: 11/20...  Training Step: 4067...  Training loss: 1.4231...  0.9382 sec/batch
Epoch: 11/20...  Training Step: 4068...  Training loss: 1.4087...  0.9291 sec/batch
Epoch: 11/20...  Training Step: 4069...  Training loss: 1.4205...  0.9324 sec/batch
Epoch: 11/20...  Training Step: 4070...  Training loss: 1.4548...  0.9327 sec/batch
Epoch: 11/20...  Training Step: 4071...  Training loss: 1.4710...  0.9312 sec/batch
Epoch: 11/20...  Training Step: 4072...  Training loss: 1.4066...  0.9283 sec/batch
Epoch: 11/20...  Training Step: 4073...  Training loss: 1.4993...  0.9414 sec/batch
Epoch: 11/20...  Training Step: 4074...  Training loss: 1.4129...  0.9292 sec/batch
Epoch: 11/20...  Training Step: 4075...  Training loss: 1.3931...  0.9190 sec/batch
Epoch: 11/20...  Training Step: 4076...  Training loss: 1.4039...  0.9341 sec/batch
Epoch: 11/20...  Training Step: 4077...  Training loss: 1.3857...  0.9242 sec/batch
Epoch: 11/20...  Training Step: 4078...  Training loss: 1.3825...  0.9321 se

Epoch: 11/20...  Training Step: 4165...  Training loss: 1.4630...  0.9388 sec/batch
Epoch: 11/20...  Training Step: 4166...  Training loss: 1.4020...  0.9738 sec/batch
Epoch: 11/20...  Training Step: 4167...  Training loss: 1.4093...  0.9326 sec/batch
Epoch: 11/20...  Training Step: 4168...  Training loss: 1.4203...  0.9276 sec/batch
Epoch: 11/20...  Training Step: 4169...  Training loss: 1.4039...  0.9409 sec/batch
Epoch: 11/20...  Training Step: 4170...  Training loss: 1.4303...  0.9392 sec/batch
Epoch: 11/20...  Training Step: 4171...  Training loss: 1.4254...  0.9324 sec/batch
Epoch: 11/20...  Training Step: 4172...  Training loss: 1.4469...  0.9269 sec/batch
Epoch: 11/20...  Training Step: 4173...  Training loss: 1.3731...  0.9299 sec/batch
Epoch: 11/20...  Training Step: 4174...  Training loss: 1.4636...  0.9274 sec/batch
Epoch: 11/20...  Training Step: 4175...  Training loss: 1.3995...  0.9253 sec/batch
Epoch: 11/20...  Training Step: 4176...  Training loss: 1.4054...  0.9382 se

Epoch: 11/20...  Training Step: 4263...  Training loss: 1.4274...  1.2722 sec/batch
Epoch: 11/20...  Training Step: 4264...  Training loss: 1.3999...  1.5104 sec/batch
Epoch: 11/20...  Training Step: 4265...  Training loss: 1.4144...  0.9665 sec/batch
Epoch: 11/20...  Training Step: 4266...  Training loss: 1.4544...  1.0482 sec/batch
Epoch: 11/20...  Training Step: 4267...  Training loss: 1.3930...  0.9545 sec/batch
Epoch: 11/20...  Training Step: 4268...  Training loss: 1.4637...  1.1462 sec/batch
Epoch: 11/20...  Training Step: 4269...  Training loss: 1.4212...  0.9917 sec/batch
Epoch: 11/20...  Training Step: 4270...  Training loss: 1.3992...  1.4379 sec/batch
Epoch: 11/20...  Training Step: 4271...  Training loss: 1.3895...  1.0902 sec/batch
Epoch: 11/20...  Training Step: 4272...  Training loss: 1.3960...  0.9342 sec/batch
Epoch: 11/20...  Training Step: 4273...  Training loss: 1.3823...  0.9811 sec/batch
Epoch: 11/20...  Training Step: 4274...  Training loss: 1.3741...  0.9311 se

Epoch: 11/20...  Training Step: 4361...  Training loss: 1.4289...  0.9331 sec/batch
Epoch: 11/20...  Training Step: 4362...  Training loss: 1.4456...  0.9209 sec/batch
Epoch: 11/20...  Training Step: 4363...  Training loss: 1.3999...  0.9390 sec/batch
Epoch: 11/20...  Training Step: 4364...  Training loss: 1.3953...  0.9312 sec/batch
Epoch: 11/20...  Training Step: 4365...  Training loss: 1.3795...  0.9280 sec/batch
Epoch: 11/20...  Training Step: 4366...  Training loss: 1.4291...  0.9287 sec/batch
Epoch: 11/20...  Training Step: 4367...  Training loss: 1.4293...  0.9292 sec/batch
Epoch: 12/20...  Training Step: 4368...  Training loss: 1.5226...  0.9291 sec/batch
Epoch: 12/20...  Training Step: 4369...  Training loss: 1.3794...  0.9484 sec/batch
Epoch: 12/20...  Training Step: 4370...  Training loss: 1.4308...  0.9351 sec/batch
Epoch: 12/20...  Training Step: 4371...  Training loss: 1.3927...  0.9319 sec/batch
Epoch: 12/20...  Training Step: 4372...  Training loss: 1.3712...  0.9321 se

Epoch: 12/20...  Training Step: 4459...  Training loss: 1.3717...  0.9327 sec/batch
Epoch: 12/20...  Training Step: 4460...  Training loss: 1.4037...  0.9302 sec/batch
Epoch: 12/20...  Training Step: 4461...  Training loss: 1.4142...  0.9274 sec/batch
Epoch: 12/20...  Training Step: 4462...  Training loss: 1.3933...  0.9307 sec/batch
Epoch: 12/20...  Training Step: 4463...  Training loss: 1.4210...  0.9304 sec/batch
Epoch: 12/20...  Training Step: 4464...  Training loss: 1.4235...  0.9500 sec/batch
Epoch: 12/20...  Training Step: 4465...  Training loss: 1.4070...  0.9379 sec/batch
Epoch: 12/20...  Training Step: 4466...  Training loss: 1.4176...  0.9285 sec/batch
Epoch: 12/20...  Training Step: 4467...  Training loss: 1.4264...  0.9288 sec/batch
Epoch: 12/20...  Training Step: 4468...  Training loss: 1.4754...  0.9383 sec/batch
Epoch: 12/20...  Training Step: 4469...  Training loss: 1.3824...  0.9274 sec/batch
Epoch: 12/20...  Training Step: 4470...  Training loss: 1.4757...  0.9319 se

Epoch: 12/20...  Training Step: 4557...  Training loss: 1.3745...  0.9378 sec/batch
Epoch: 12/20...  Training Step: 4558...  Training loss: 1.4010...  0.9332 sec/batch
Epoch: 12/20...  Training Step: 4559...  Training loss: 1.4530...  1.0280 sec/batch
Epoch: 12/20...  Training Step: 4560...  Training loss: 1.4130...  0.9989 sec/batch
Epoch: 12/20...  Training Step: 4561...  Training loss: 1.3994...  0.9773 sec/batch
Epoch: 12/20...  Training Step: 4562...  Training loss: 1.4481...  0.9424 sec/batch
Epoch: 12/20...  Training Step: 4563...  Training loss: 1.4093...  0.9917 sec/batch
Epoch: 12/20...  Training Step: 4564...  Training loss: 1.4073...  0.9390 sec/batch
Epoch: 12/20...  Training Step: 4565...  Training loss: 1.4149...  0.9249 sec/batch
Epoch: 12/20...  Training Step: 4566...  Training loss: 1.4056...  0.9302 sec/batch
Epoch: 12/20...  Training Step: 4567...  Training loss: 1.4196...  0.9328 sec/batch
Epoch: 12/20...  Training Step: 4568...  Training loss: 1.4256...  0.9224 se

Epoch: 12/20...  Training Step: 4655...  Training loss: 1.4141...  0.9198 sec/batch
Epoch: 12/20...  Training Step: 4656...  Training loss: 1.4013...  0.9893 sec/batch
Epoch: 12/20...  Training Step: 4657...  Training loss: 1.3494...  0.9356 sec/batch
Epoch: 12/20...  Training Step: 4658...  Training loss: 1.3706...  0.9269 sec/batch
Epoch: 12/20...  Training Step: 4659...  Training loss: 1.4125...  0.9227 sec/batch
Epoch: 12/20...  Training Step: 4660...  Training loss: 1.4170...  0.9278 sec/batch
Epoch: 12/20...  Training Step: 4661...  Training loss: 1.3926...  0.9252 sec/batch
Epoch: 12/20...  Training Step: 4662...  Training loss: 1.3925...  0.9297 sec/batch
Epoch: 12/20...  Training Step: 4663...  Training loss: 1.4476...  0.9329 sec/batch
Epoch: 12/20...  Training Step: 4664...  Training loss: 1.3996...  0.9303 sec/batch
Epoch: 12/20...  Training Step: 4665...  Training loss: 1.4486...  0.9309 sec/batch
Epoch: 12/20...  Training Step: 4666...  Training loss: 1.4030...  0.9280 se

Epoch: 12/20...  Training Step: 4753...  Training loss: 1.3805...  0.9295 sec/batch
Epoch: 12/20...  Training Step: 4754...  Training loss: 1.4347...  0.9230 sec/batch
Epoch: 12/20...  Training Step: 4755...  Training loss: 1.3946...  0.9225 sec/batch
Epoch: 12/20...  Training Step: 4756...  Training loss: 1.3969...  0.9273 sec/batch
Epoch: 12/20...  Training Step: 4757...  Training loss: 1.4574...  0.9305 sec/batch
Epoch: 12/20...  Training Step: 4758...  Training loss: 1.4170...  0.9364 sec/batch
Epoch: 12/20...  Training Step: 4759...  Training loss: 1.4347...  0.9264 sec/batch
Epoch: 12/20...  Training Step: 4760...  Training loss: 1.3939...  0.9240 sec/batch
Epoch: 12/20...  Training Step: 4761...  Training loss: 1.3902...  0.9313 sec/batch
Epoch: 12/20...  Training Step: 4762...  Training loss: 1.3764...  0.9317 sec/batch
Epoch: 12/20...  Training Step: 4763...  Training loss: 1.4136...  0.9400 sec/batch
Epoch: 12/20...  Training Step: 4764...  Training loss: 1.4270...  0.9339 se

Epoch: 13/20...  Training Step: 4851...  Training loss: 1.4504...  0.9370 sec/batch
Epoch: 13/20...  Training Step: 4852...  Training loss: 1.4305...  0.9363 sec/batch
Epoch: 13/20...  Training Step: 4853...  Training loss: 1.4255...  0.9294 sec/batch
Epoch: 13/20...  Training Step: 4854...  Training loss: 1.4394...  0.9328 sec/batch
Epoch: 13/20...  Training Step: 4855...  Training loss: 1.3901...  0.9304 sec/batch
Epoch: 13/20...  Training Step: 4856...  Training loss: 1.3774...  0.9263 sec/batch
Epoch: 13/20...  Training Step: 4857...  Training loss: 1.4152...  0.9316 sec/batch
Epoch: 13/20...  Training Step: 4858...  Training loss: 1.4020...  0.9395 sec/batch
Epoch: 13/20...  Training Step: 4859...  Training loss: 1.3871...  0.9227 sec/batch
Epoch: 13/20...  Training Step: 4860...  Training loss: 1.4295...  0.9329 sec/batch
Epoch: 13/20...  Training Step: 4861...  Training loss: 1.4096...  0.9295 sec/batch
Epoch: 13/20...  Training Step: 4862...  Training loss: 1.3970...  0.9362 se

Epoch: 13/20...  Training Step: 4949...  Training loss: 1.3632...  0.9248 sec/batch
Epoch: 13/20...  Training Step: 4950...  Training loss: 1.3948...  0.9413 sec/batch
Epoch: 13/20...  Training Step: 4951...  Training loss: 1.3958...  0.9282 sec/batch
Epoch: 13/20...  Training Step: 4952...  Training loss: 1.3323...  0.9303 sec/batch
Epoch: 13/20...  Training Step: 4953...  Training loss: 1.3977...  0.9248 sec/batch
Epoch: 13/20...  Training Step: 4954...  Training loss: 1.3857...  0.9346 sec/batch
Epoch: 13/20...  Training Step: 4955...  Training loss: 1.4087...  0.9307 sec/batch
Epoch: 13/20...  Training Step: 4956...  Training loss: 1.4389...  0.9314 sec/batch
Epoch: 13/20...  Training Step: 4957...  Training loss: 1.4101...  0.9280 sec/batch
Epoch: 13/20...  Training Step: 4958...  Training loss: 1.3895...  0.9325 sec/batch
Epoch: 13/20...  Training Step: 4959...  Training loss: 1.4409...  0.9302 sec/batch
Epoch: 13/20...  Training Step: 4960...  Training loss: 1.4008...  0.9396 se

Epoch: 13/20...  Training Step: 5047...  Training loss: 1.3846...  0.9498 sec/batch
Epoch: 13/20...  Training Step: 5048...  Training loss: 1.4170...  0.9277 sec/batch
Epoch: 13/20...  Training Step: 5049...  Training loss: 1.3351...  0.9279 sec/batch
Epoch: 13/20...  Training Step: 5050...  Training loss: 1.3733...  0.9390 sec/batch
Epoch: 13/20...  Training Step: 5051...  Training loss: 1.4111...  0.9300 sec/batch
Epoch: 13/20...  Training Step: 5052...  Training loss: 1.3993...  0.9523 sec/batch
Epoch: 13/20...  Training Step: 5053...  Training loss: 1.4154...  0.9195 sec/batch
Epoch: 13/20...  Training Step: 5054...  Training loss: 1.3604...  0.9215 sec/batch
Epoch: 13/20...  Training Step: 5055...  Training loss: 1.3667...  0.9121 sec/batch
Epoch: 13/20...  Training Step: 5056...  Training loss: 1.3910...  0.9401 sec/batch
Epoch: 13/20...  Training Step: 5057...  Training loss: 1.4179...  0.9356 sec/batch
Epoch: 13/20...  Training Step: 5058...  Training loss: 1.3939...  0.9415 se

Epoch: 13/20...  Training Step: 5145...  Training loss: 1.4024...  0.9252 sec/batch
Epoch: 13/20...  Training Step: 5146...  Training loss: 1.3772...  0.9223 sec/batch
Epoch: 13/20...  Training Step: 5147...  Training loss: 1.4215...  0.9345 sec/batch
Epoch: 13/20...  Training Step: 5148...  Training loss: 1.4189...  0.9340 sec/batch
Epoch: 13/20...  Training Step: 5149...  Training loss: 1.3656...  0.9384 sec/batch
Epoch: 13/20...  Training Step: 5150...  Training loss: 1.3936...  0.9219 sec/batch
Epoch: 13/20...  Training Step: 5151...  Training loss: 1.4384...  0.9161 sec/batch
Epoch: 13/20...  Training Step: 5152...  Training loss: 1.3928...  0.9323 sec/batch
Epoch: 13/20...  Training Step: 5153...  Training loss: 1.4041...  0.9330 sec/batch
Epoch: 13/20...  Training Step: 5154...  Training loss: 1.4467...  0.9327 sec/batch
Epoch: 13/20...  Training Step: 5155...  Training loss: 1.4121...  0.9319 sec/batch
Epoch: 13/20...  Training Step: 5156...  Training loss: 1.4376...  0.9226 se

Epoch: 14/20...  Training Step: 5243...  Training loss: 1.3932...  0.9254 sec/batch
Epoch: 14/20...  Training Step: 5244...  Training loss: 1.4151...  0.9363 sec/batch
Epoch: 14/20...  Training Step: 5245...  Training loss: 1.4048...  0.9368 sec/batch
Epoch: 14/20...  Training Step: 5246...  Training loss: 1.3994...  0.9248 sec/batch
Epoch: 14/20...  Training Step: 5247...  Training loss: 1.3774...  0.9269 sec/batch
Epoch: 14/20...  Training Step: 5248...  Training loss: 1.4583...  0.9219 sec/batch
Epoch: 14/20...  Training Step: 5249...  Training loss: 1.4187...  0.9337 sec/batch
Epoch: 14/20...  Training Step: 5250...  Training loss: 1.4360...  0.9383 sec/batch
Epoch: 14/20...  Training Step: 5251...  Training loss: 1.4368...  0.9134 sec/batch
Epoch: 14/20...  Training Step: 5252...  Training loss: 1.4112...  0.9230 sec/batch
Epoch: 14/20...  Training Step: 5253...  Training loss: 1.3832...  0.9277 sec/batch
Epoch: 14/20...  Training Step: 5254...  Training loss: 1.4054...  0.9190 se

Epoch: 14/20...  Training Step: 5341...  Training loss: 1.4039...  0.9466 sec/batch
Epoch: 14/20...  Training Step: 5342...  Training loss: 1.3827...  0.9238 sec/batch
Epoch: 14/20...  Training Step: 5343...  Training loss: 1.4212...  0.9412 sec/batch
Epoch: 14/20...  Training Step: 5344...  Training loss: 1.4183...  0.9305 sec/batch
Epoch: 14/20...  Training Step: 5345...  Training loss: 1.3861...  0.9276 sec/batch
Epoch: 14/20...  Training Step: 5346...  Training loss: 1.3705...  0.9315 sec/batch
Epoch: 14/20...  Training Step: 5347...  Training loss: 1.3815...  0.9312 sec/batch
Epoch: 14/20...  Training Step: 5348...  Training loss: 1.3946...  0.9304 sec/batch
Epoch: 14/20...  Training Step: 5349...  Training loss: 1.3261...  0.9303 sec/batch
Epoch: 14/20...  Training Step: 5350...  Training loss: 1.4048...  0.9330 sec/batch
Epoch: 14/20...  Training Step: 5351...  Training loss: 1.3669...  0.9117 sec/batch
Epoch: 14/20...  Training Step: 5352...  Training loss: 1.3868...  0.9353 se

Epoch: 14/20...  Training Step: 5439...  Training loss: 1.3930...  0.9312 sec/batch
Epoch: 14/20...  Training Step: 5440...  Training loss: 1.3730...  0.9302 sec/batch
Epoch: 14/20...  Training Step: 5441...  Training loss: 1.4415...  0.9316 sec/batch
Epoch: 14/20...  Training Step: 5442...  Training loss: 1.3672...  0.9377 sec/batch
Epoch: 14/20...  Training Step: 5443...  Training loss: 1.3889...  0.9369 sec/batch
Epoch: 14/20...  Training Step: 5444...  Training loss: 1.3882...  0.9247 sec/batch
Epoch: 14/20...  Training Step: 5445...  Training loss: 1.4003...  0.9293 sec/batch
Epoch: 14/20...  Training Step: 5446...  Training loss: 1.3253...  0.9259 sec/batch
Epoch: 14/20...  Training Step: 5447...  Training loss: 1.3742...  0.9311 sec/batch
Epoch: 14/20...  Training Step: 5448...  Training loss: 1.4176...  0.9279 sec/batch
Epoch: 14/20...  Training Step: 5449...  Training loss: 1.3896...  0.9279 sec/batch
Epoch: 14/20...  Training Step: 5450...  Training loss: 1.3987...  0.9214 se

Epoch: 14/20...  Training Step: 5537...  Training loss: 1.3760...  0.9268 sec/batch
Epoch: 14/20...  Training Step: 5538...  Training loss: 1.4022...  0.9318 sec/batch
Epoch: 14/20...  Training Step: 5539...  Training loss: 1.4044...  0.9313 sec/batch
Epoch: 14/20...  Training Step: 5540...  Training loss: 1.4031...  0.9227 sec/batch
Epoch: 14/20...  Training Step: 5541...  Training loss: 1.3843...  0.9273 sec/batch
Epoch: 14/20...  Training Step: 5542...  Training loss: 1.4096...  0.9321 sec/batch
Epoch: 14/20...  Training Step: 5543...  Training loss: 1.3774...  0.9195 sec/batch
Epoch: 14/20...  Training Step: 5544...  Training loss: 1.4301...  0.9418 sec/batch
Epoch: 14/20...  Training Step: 5545...  Training loss: 1.4142...  0.9307 sec/batch
Epoch: 14/20...  Training Step: 5546...  Training loss: 1.3680...  0.9206 sec/batch
Epoch: 14/20...  Training Step: 5547...  Training loss: 1.3871...  0.9319 sec/batch
Epoch: 14/20...  Training Step: 5548...  Training loss: 1.4207...  1.0098 se

Epoch: 15/20...  Training Step: 5635...  Training loss: 1.5013...  0.9271 sec/batch
Epoch: 15/20...  Training Step: 5636...  Training loss: 1.4024...  0.9352 sec/batch
Epoch: 15/20...  Training Step: 5637...  Training loss: 1.4047...  0.9287 sec/batch
Epoch: 15/20...  Training Step: 5638...  Training loss: 1.4006...  0.9218 sec/batch
Epoch: 15/20...  Training Step: 5639...  Training loss: 1.3923...  0.9295 sec/batch
Epoch: 15/20...  Training Step: 5640...  Training loss: 1.3796...  0.9326 sec/batch
Epoch: 15/20...  Training Step: 5641...  Training loss: 1.4221...  0.9170 sec/batch
Epoch: 15/20...  Training Step: 5642...  Training loss: 1.4088...  0.9253 sec/batch
Epoch: 15/20...  Training Step: 5643...  Training loss: 1.3899...  0.9219 sec/batch
Epoch: 15/20...  Training Step: 5644...  Training loss: 1.3749...  0.9319 sec/batch
Epoch: 15/20...  Training Step: 5645...  Training loss: 1.4413...  0.9313 sec/batch
Epoch: 15/20...  Training Step: 5646...  Training loss: 1.4052...  0.9319 se

Epoch: 15/20...  Training Step: 5733...  Training loss: 1.4065...  0.9366 sec/batch
Epoch: 15/20...  Training Step: 5734...  Training loss: 1.3310...  0.9301 sec/batch
Epoch: 15/20...  Training Step: 5735...  Training loss: 1.3890...  0.9337 sec/batch
Epoch: 15/20...  Training Step: 5736...  Training loss: 1.3377...  0.9245 sec/batch
Epoch: 15/20...  Training Step: 5737...  Training loss: 1.3639...  0.9159 sec/batch
Epoch: 15/20...  Training Step: 5738...  Training loss: 1.3993...  0.9274 sec/batch
Epoch: 15/20...  Training Step: 5739...  Training loss: 1.3833...  0.9272 sec/batch
Epoch: 15/20...  Training Step: 5740...  Training loss: 1.4006...  0.9344 sec/batch
Epoch: 15/20...  Training Step: 5741...  Training loss: 1.4089...  0.9356 sec/batch
Epoch: 15/20...  Training Step: 5742...  Training loss: 1.3765...  0.9876 sec/batch
Epoch: 15/20...  Training Step: 5743...  Training loss: 1.3616...  0.9221 sec/batch
Epoch: 15/20...  Training Step: 5744...  Training loss: 1.3941...  0.9297 se

Epoch: 15/20...  Training Step: 5831...  Training loss: 1.4196...  0.9393 sec/batch
Epoch: 15/20...  Training Step: 5832...  Training loss: 1.4257...  0.9320 sec/batch
Epoch: 15/20...  Training Step: 5833...  Training loss: 1.4511...  0.9297 sec/batch
Epoch: 15/20...  Training Step: 5834...  Training loss: 1.4094...  0.9266 sec/batch
Epoch: 15/20...  Training Step: 5835...  Training loss: 1.3665...  0.9306 sec/batch
Epoch: 15/20...  Training Step: 5836...  Training loss: 1.3968...  0.9365 sec/batch
Epoch: 15/20...  Training Step: 5837...  Training loss: 1.3743...  0.9390 sec/batch
Epoch: 15/20...  Training Step: 5838...  Training loss: 1.4383...  0.9183 sec/batch
Epoch: 15/20...  Training Step: 5839...  Training loss: 1.3493...  0.9299 sec/batch
Epoch: 15/20...  Training Step: 5840...  Training loss: 1.4006...  0.9309 sec/batch
Epoch: 15/20...  Training Step: 5841...  Training loss: 1.3852...  0.9272 sec/batch
Epoch: 15/20...  Training Step: 5842...  Training loss: 1.4013...  0.9299 se

Epoch: 15/20...  Training Step: 5929...  Training loss: 1.3727...  0.9283 sec/batch
Epoch: 15/20...  Training Step: 5930...  Training loss: 1.3933...  0.9342 sec/batch
Epoch: 15/20...  Training Step: 5931...  Training loss: 1.4150...  0.9251 sec/batch
Epoch: 15/20...  Training Step: 5932...  Training loss: 1.3981...  0.9282 sec/batch
Epoch: 15/20...  Training Step: 5933...  Training loss: 1.4013...  1.0165 sec/batch
Epoch: 15/20...  Training Step: 5934...  Training loss: 1.3711...  0.9323 sec/batch
Epoch: 15/20...  Training Step: 5935...  Training loss: 1.4017...  0.9883 sec/batch
Epoch: 15/20...  Training Step: 5936...  Training loss: 1.3890...  0.9392 sec/batch
Epoch: 15/20...  Training Step: 5937...  Training loss: 1.3892...  0.9315 sec/batch
Epoch: 15/20...  Training Step: 5938...  Training loss: 1.3877...  0.9357 sec/batch
Epoch: 15/20...  Training Step: 5939...  Training loss: 1.4027...  0.9320 sec/batch
Epoch: 15/20...  Training Step: 5940...  Training loss: 1.3603...  0.9357 se

Epoch: 16/20...  Training Step: 6027...  Training loss: 1.3849...  0.9199 sec/batch
Epoch: 16/20...  Training Step: 6028...  Training loss: 1.3987...  0.9321 sec/batch
Epoch: 16/20...  Training Step: 6029...  Training loss: 1.3891...  0.9273 sec/batch
Epoch: 16/20...  Training Step: 6030...  Training loss: 1.4144...  0.9175 sec/batch
Epoch: 16/20...  Training Step: 6031...  Training loss: 1.4268...  0.9215 sec/batch
Epoch: 16/20...  Training Step: 6032...  Training loss: 1.4855...  0.9249 sec/batch
Epoch: 16/20...  Training Step: 6033...  Training loss: 1.3701...  0.9317 sec/batch
Epoch: 16/20...  Training Step: 6034...  Training loss: 1.3856...  0.9282 sec/batch
Epoch: 16/20...  Training Step: 6035...  Training loss: 1.3858...  0.9378 sec/batch
Epoch: 16/20...  Training Step: 6036...  Training loss: 1.3878...  0.9304 sec/batch
Epoch: 16/20...  Training Step: 6037...  Training loss: 1.3819...  0.9242 sec/batch
Epoch: 16/20...  Training Step: 6038...  Training loss: 1.4127...  0.9296 se

Epoch: 16/20...  Training Step: 6125...  Training loss: 1.4092...  0.9299 sec/batch
Epoch: 16/20...  Training Step: 6126...  Training loss: 1.3666...  0.9343 sec/batch
Epoch: 16/20...  Training Step: 6127...  Training loss: 1.3489...  0.9256 sec/batch
Epoch: 16/20...  Training Step: 6128...  Training loss: 1.4021...  0.9247 sec/batch
Epoch: 16/20...  Training Step: 6129...  Training loss: 1.3968...  0.9183 sec/batch
Epoch: 16/20...  Training Step: 6130...  Training loss: 1.4070...  0.9334 sec/batch
Epoch: 16/20...  Training Step: 6131...  Training loss: 1.3293...  0.9297 sec/batch
Epoch: 16/20...  Training Step: 6132...  Training loss: 1.3713...  0.9311 sec/batch
Epoch: 16/20...  Training Step: 6133...  Training loss: 1.3445...  0.9403 sec/batch
Epoch: 16/20...  Training Step: 6134...  Training loss: 1.3491...  0.9288 sec/batch
Epoch: 16/20...  Training Step: 6135...  Training loss: 1.3985...  0.9242 sec/batch
Epoch: 16/20...  Training Step: 6136...  Training loss: 1.3914...  0.9234 se

Epoch: 16/20...  Training Step: 6223...  Training loss: 1.3571...  0.9235 sec/batch
Epoch: 16/20...  Training Step: 6224...  Training loss: 1.4387...  0.9223 sec/batch
Epoch: 16/20...  Training Step: 6225...  Training loss: 1.4494...  0.9275 sec/batch
Epoch: 16/20...  Training Step: 6226...  Training loss: 1.3965...  0.9142 sec/batch
Epoch: 16/20...  Training Step: 6227...  Training loss: 1.3885...  0.9256 sec/batch
Epoch: 16/20...  Training Step: 6228...  Training loss: 1.3984...  0.9264 sec/batch
Epoch: 16/20...  Training Step: 6229...  Training loss: 1.4170...  0.9299 sec/batch
Epoch: 16/20...  Training Step: 6230...  Training loss: 1.4320...  0.9339 sec/batch
Epoch: 16/20...  Training Step: 6231...  Training loss: 1.3980...  0.9327 sec/batch
Epoch: 16/20...  Training Step: 6232...  Training loss: 1.3630...  0.9328 sec/batch
Epoch: 16/20...  Training Step: 6233...  Training loss: 1.3781...  0.9312 sec/batch
Epoch: 16/20...  Training Step: 6234...  Training loss: 1.3880...  0.9302 se

Epoch: 16/20...  Training Step: 6321...  Training loss: 1.4493...  1.3945 sec/batch
Epoch: 16/20...  Training Step: 6322...  Training loss: 1.4038...  2.4350 sec/batch
Epoch: 16/20...  Training Step: 6323...  Training loss: 1.4017...  2.3118 sec/batch
Epoch: 16/20...  Training Step: 6324...  Training loss: 1.4102...  1.5292 sec/batch
Epoch: 16/20...  Training Step: 6325...  Training loss: 1.3731...  1.2672 sec/batch
Epoch: 16/20...  Training Step: 6326...  Training loss: 1.3773...  1.1298 sec/batch
Epoch: 16/20...  Training Step: 6327...  Training loss: 1.3962...  1.3838 sec/batch
Epoch: 16/20...  Training Step: 6328...  Training loss: 1.4192...  0.9448 sec/batch
Epoch: 16/20...  Training Step: 6329...  Training loss: 1.3982...  0.9446 sec/batch
Epoch: 16/20...  Training Step: 6330...  Training loss: 1.3914...  0.9337 sec/batch
Epoch: 16/20...  Training Step: 6331...  Training loss: 1.3664...  0.9267 sec/batch
Epoch: 16/20...  Training Step: 6332...  Training loss: 1.4023...  0.9284 se

Epoch: 17/20...  Training Step: 6419...  Training loss: 1.3739...  0.9349 sec/batch
Epoch: 17/20...  Training Step: 6420...  Training loss: 1.3968...  0.9367 sec/batch
Epoch: 17/20...  Training Step: 6421...  Training loss: 1.4283...  0.9089 sec/batch
Epoch: 17/20...  Training Step: 6422...  Training loss: 1.4129...  0.9182 sec/batch
Epoch: 17/20...  Training Step: 6423...  Training loss: 1.4423...  0.9239 sec/batch
Epoch: 17/20...  Training Step: 6424...  Training loss: 1.3815...  0.9163 sec/batch
Epoch: 17/20...  Training Step: 6425...  Training loss: 1.3912...  0.9195 sec/batch
Epoch: 17/20...  Training Step: 6426...  Training loss: 1.3971...  0.9305 sec/batch
Epoch: 17/20...  Training Step: 6427...  Training loss: 1.4256...  0.9288 sec/batch
Epoch: 17/20...  Training Step: 6428...  Training loss: 1.4211...  0.9318 sec/batch
Epoch: 17/20...  Training Step: 6429...  Training loss: 1.4814...  0.9312 sec/batch
Epoch: 17/20...  Training Step: 6430...  Training loss: 1.3818...  0.9326 se

Epoch: 17/20...  Training Step: 6517...  Training loss: 1.3978...  0.9377 sec/batch
Epoch: 17/20...  Training Step: 6518...  Training loss: 1.4279...  0.9302 sec/batch
Epoch: 17/20...  Training Step: 6519...  Training loss: 1.3639...  0.9232 sec/batch
Epoch: 17/20...  Training Step: 6520...  Training loss: 1.3765...  0.9273 sec/batch
Epoch: 17/20...  Training Step: 6521...  Training loss: 1.3417...  0.9203 sec/batch
Epoch: 17/20...  Training Step: 6522...  Training loss: 1.4049...  0.9261 sec/batch
Epoch: 17/20...  Training Step: 6523...  Training loss: 1.3875...  0.9341 sec/batch
Epoch: 17/20...  Training Step: 6524...  Training loss: 1.3571...  0.9286 sec/batch
Epoch: 17/20...  Training Step: 6525...  Training loss: 1.3973...  0.9211 sec/batch
Epoch: 17/20...  Training Step: 6526...  Training loss: 1.3819...  0.9210 sec/batch
Epoch: 17/20...  Training Step: 6527...  Training loss: 1.4020...  0.9253 sec/batch
Epoch: 17/20...  Training Step: 6528...  Training loss: 1.3291...  0.9369 se

Epoch: 17/20...  Training Step: 6615...  Training loss: 1.3641...  0.9431 sec/batch
Epoch: 17/20...  Training Step: 6616...  Training loss: 1.4323...  0.9371 sec/batch
Epoch: 17/20...  Training Step: 6617...  Training loss: 1.3936...  0.9241 sec/batch
Epoch: 17/20...  Training Step: 6618...  Training loss: 1.4275...  0.9224 sec/batch
Epoch: 17/20...  Training Step: 6619...  Training loss: 1.4232...  0.9369 sec/batch
Epoch: 17/20...  Training Step: 6620...  Training loss: 1.3453...  1.1329 sec/batch
Epoch: 17/20...  Training Step: 6621...  Training loss: 1.4373...  1.3333 sec/batch
Epoch: 17/20...  Training Step: 6622...  Training loss: 1.4233...  1.0506 sec/batch
Epoch: 17/20...  Training Step: 6623...  Training loss: 1.3815...  0.9485 sec/batch
Epoch: 17/20...  Training Step: 6624...  Training loss: 1.3942...  0.9582 sec/batch
Epoch: 17/20...  Training Step: 6625...  Training loss: 1.3987...  0.9586 sec/batch
Epoch: 17/20...  Training Step: 6626...  Training loss: 1.4131...  1.0367 se

KeyboardInterrupt: 

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [ ]:
tf.train.get_checkpoint_state('checkpoints')

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [ ]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [ ]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [ ]:
tf.train.latest_checkpoint('checkpoints')

In [ ]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)