In [2]:
import numpy as np

s = np.array(5)
print(s)

5


In [37]:
s.shape

()

In [38]:
x = s + 3
print(x)

8


In [39]:
v = np.array([1,2,3])
print(v)

[1 2 3]


In [40]:
v.shape

(3,)

In [41]:
x = v[1]
print(x)

2


In [42]:
from_second = v[1:]
print(from_second)

[2 3]


In [43]:
m = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
m.shape

(3, 3)

In [45]:
element_wise = m*m

In [46]:
print(element_wise)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [19]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [20]:
t.shape

(3, 3, 2, 1)

In [24]:
#values = [1, 2, 3, 4, 5]
values = np.array([1, 2, 3, 4, 5])
values += 5
print(values)

[ 6  7  8  9 10]


In [26]:
x = np.array([1, 2, 3, 4, 5])
x *= 5 
print(x)

[ 5 10 15 20 25]


In [27]:
a = np.array([[1,3],[5,7]])
b = np.array([[2,4],[6,8]])
print(a)
print(b)

[[1 3]
 [5 7]]
[[2 4]
 [6 8]]


In [28]:
a+b

array([[ 3,  7],
       [11, 15]])

In [29]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])

(3, 3)

In [30]:
a.shape

(2, 2)

In [31]:
c.shape

(3, 3)

In [3]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [6]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [8]:
a.dot(a) 

array([[ 7, 10],
       [15, 22]])

In [9]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

In [10]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [12]:
m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [13]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

In [14]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [15]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [16]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [17]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

## Numpy Exam

In [36]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to new_inputs
    input_array = np.array([inputs])
    # print(input_array)
    # print(input_array.shape)
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    # min_input = 100000
    # for row in input_array:
    #    for element in row:
    #        if element < min_input:
    #            min_input = element
    # print(min_input)
    min_input = input_array.min()
    inputs_minus_min = input_array - min_input
    # print(inputs_minus_min)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    max_input = inputs_minus_min.max()
    inputs_div_max = inputs_minus_min / max_input

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    shape_m1 = m1.shape
    shape_m2 = m2.shape
    if shape_m1[0] != shape_m2[1] and shape_m1[1] != shape_m2[0]:
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if shape_m1[1] == shape_m2[0]:
        return np.matmul(m1, m2)
    else:
        return np.matmul(m2, m1)
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[ 0.     0.375  1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
